### ISSUE TITLE
What is the purpose of this repo?

### ISSUE THREAD

**Issue by milanmp** [oatpp/example-jwt#1]
Looks like there was a nice idea to create JWT example 7 months ago but it simply did not happen?
I would expect that example repos are created when they have a purpose, this way they are useless and just add to a noise.
This is a plain copy of crud example that has not been worked on...
If there are no plans to update this example it is better to remove it...

**Comment by lganzzzo** [comment]
Hello @milanmpetrovic , 

This will be an example of a service with JWT.
It will be updated together with a release of oatpp `1.3.0`

**Comment by milanmp** [comment]
Hello @lganzzzo,

Thank you for a quick response. Looking forward to it.

If it matters I stumbled upon this example repo since I had an issue with using authorisation in combination with Swagger, got "Error. Authorized endpoint with no security requirements (info->addSecurityRequirement())" and realised meanwhile that Api Docs are not automatically generated for Authorisation part of the endpoint.  Unfortunately could not find any example in Oatpp docs nor code on how Simple API annotations supose to be added for Basic or Bearer authorisation. Would be quite handy to have those.
Update: meanwhile I found extra info at the end of oatpp-swagger/README.md which helps for this matter.

**Comment by lganzzzo** [comment]
Yeah, this info is a bit shredded among different places.
Hopefully, this repo will fix that.

**Comment by milanmp** [comment]
> Hello @milanmpetrovic ,
> 
> This will be an example of a service with JWT. It will be updated together with a release of oatpp `1.3.0`

and ... :) friendly reminder

**Comment by lganzzzo** [comment]
Hey @milanmpetrovic ,
I'm really close :)
Just have to finish stuff like password hashing and UUID generation

**Comment by lganzzzo** [comment]
Hey @milanmpetrovic ,
This project is still in the draft however, most of the functionality is ready and working.
So you can start playing with it.

**Comment by milanmp** [comment]
Great, thanks!

**Comment by lganzzzo** [comment]
Oh, I see, you were interested in the swagger part particularly... I'll add this too, soon.

**Comment by manjus3** [comment]
Hi @lganzzzo, this is a very useful example, but I'm having issues with it. I'm trying to run this repo on my Ubuntu 22.04 machine. It compiles fine, but core dumps immediately:
manju@manju-virtual-machine:~/tools/oatpp_repos/examples/example-jwt/build$ ./example-jwt-exe 
Segmentation fault (core dumped)

It seems to be crashing the call to PQconnectdb() from /home/manju/tools/oatpp_repos/oatpp-postgresql/src/oatpp-postgresql/ConnectionProvider.cpp:43

Thanks,
Manju

And here's the stack trace:
manju@manju-virtual-machine:~/tools/oatpp_repos/examples/example-jwt/build$ ./example-jwt-exe 
Segmentation fault (core dumped)
(gdb) r
Starting program: /home/manju/tools/oatpp_repos/examples/example-jwt/build/example-jwt-exe 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff5b53640 (LWP 135991)]

Thread 1 "example-jwt-exe" received signal SIGSEGV, Segmentation fault.
0x00007ffff767290d in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.3
(gdb) bt
#0  0x00007ffff767290d in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.3
#1  0x00007ffff7678c5b in ENGINE_init () from /lib/x86_64-linux-gnu/libcrypto.so.3
#2  0x00007ffff76aefa1 in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.3
#3  0x00007ffff79843d3 in SSL_CTX_new_ex () from /lib/x86_64-linux-gnu/libssl.so.3
#4  0x00007ffff7f7f3dd in ?? () from /lib/x86_64-linux-gnu/libpq.so.5
#5  0x00007ffff7f68e1a in PQconnectPoll () from /lib/x86_64-linux-gnu/libpq.so.5
#6  0x00007ffff7f6ae10 in ?? () from /lib/x86_64-linux-gnu/libpq.so.5
#7  0x00007ffff7f6af08 in PQconnectdb () from /lib/x86_64-linux-gnu/libpq.so.5
#8  0x0000555555f04abc in oatpp::postgresql::ConnectionProvider::get (this=0x5555563c3db0)
    at /home/manju/tools/oatpp_repos/oatpp-postgresql/src/oatpp-postgresql/ConnectionProvider.cpp:43
#9  0x0000555555e347df in oatpp::provider::PoolTemplate<oatpp::postgresql::Connection, oatpp::postgresql::ConnectionAcquisitionProxy>::get (_this=warning: RTTI symbol not found for class 'std::_Sp_counted_ptr<oatpp::provider::Pool<oatpp::provider::Provider<oatpp::postgresql::Connection>, oatpp::postgresql::Connection, oatpp::postgresql::ConnectionAcquisitionProxy>*, (__gnu_cxx::_Lock_policy)2>'
warning: RTTI symbol not found for class 'std::_Sp_counted_ptr<oatpp::provider::Pool<oatpp::provider::Provider<oatpp::postgresql::Connection>, oatpp::postgresql::Connection, oatpp::postgresql::ConnectionAcquisitionProxy>*, (__gnu_cxx::_Lock_policy)2>'

std::shared_ptr<oatpp::provider::PoolTemplate<oatpp::postgresql::Connection, oatpp::postgresql::ConnectionAcquisitionProxy>> (use count 4, weak count 1) = {...})
    at /usr/local/include/oatpp-1.3.0/oatpp/oatpp/core/provider/Pool.hpp:266
#10 0x0000555555e3047e in oatpp::provider::Pool<oatpp::provider::Provider<oatpp::postgresql::Connection>, oatpp::postgresql::Connection, oatpp::postgresql::ConnectionAcquisitionProxy>::get (this=0x5555563c53d0) at /usr/local/include/oatpp-1.3.0/oatpp/oatpp/core/provider/Pool.hpp:462
#11 0x0000555555f0863c in oatpp::postgresql::Executor::getConnection (this=0x5555563c56f0) at /home/manju/tools/oatpp_repos/oatpp-postgresql/src/oatpp-postgresql/Executor.cpp:299
#12 0x00005555560429cc in oatpp::orm::SchemaMigration::migrate (this=0x7fffffffcbd0) at /home/manju/tools/oatpp_repos/oatpp/src/oatpp/orm/SchemaMigration.cpp:50
#13 0x0000555555e3c04b in UserDb::UserDb (this=0x5555563c4810, executor=warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<oatpp::postgresql::Executor, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<oatpp::postgresql::Executor, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
std::shared_ptr<oatpp::orm::Executor> (use count 4, weak count 0) = {...})
    at /home/manju/tools/oatpp_repos/examples/example-jwt/src/db/UserDb.hpp:23
#14 0x0000555555e3be8e in std::_Construct<UserDb, std::shared_ptr<oatpp::postgresql::Executor>&> (__p=0x5555563c4810, __args=warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<oatpp::postgresql::Executor, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<oatpp::postgresql::Executor, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'

std::shared_ptr<oatpp::postgresql::Executor> (use count 4, weak count 0) = {...}) at /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/stl_construct.h:119
#15 0x0000555555e3bcd1 in std::allocator_traits<std::allocator<void> >::construct<UserDb, std::shared_ptr<oatpp::postgresql::Executor>&> (__p=0x5555563c4810, __args=warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<oatpp::postgresql::Executor, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<oatpp::postgresql::Executor, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'

std::shared_ptr<oatpp::postgresql::Executor> (use count 4, weak count 0) = {...}) at /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/alloc_traits.h:635
#16 0x0000555555e3ba6a in std::_Sp_counted_ptr_inplace<UserDb, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<std::shared_ptr<oatpp::postgresql::Executor>&> (this=0x5555563c4800, __a=..., __args=warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<oatpp::postgresql::Executor, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<oatpp::postgresql::Executor, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
std::shared_ptr<oatpp::postgresql::Executor> (use count 4, weak count 0) = {...})
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/shared_ptr_base.h:604
#17 0x0000555555e3b8dd in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<UserDb, std::allocator<void>, std::shared_ptr<oatpp::postgresql::Executor>&> (
    this=0x7fffffffcf50, __p=@0x7fffffffcf48: 0x0, __a=..., __args=warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<oatpp::postgresql::Executor, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<oatpp::postgresql::Executor, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
std::shared_ptr<oatpp::postgresql::Executor> (use count 4, weak count 0) = {...})
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/shared_ptr_base.h:972
#18 0x0000555555e3b840 in std::__shared_ptr<UserDb, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<void>, std::shared_ptr<oatpp::postgresql::Executor>&> (
    this=0x7fffffffcf48, __tag=..., __args=warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<oatpp::postgresql::Executor, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<oatpp::postgresql::Executor, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
std::shared_ptr<oatpp::postgresql::Executor> (use count 4, weak count 0) = {...})
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/shared_ptr_base.h:1712
#19 0x0000555555e3b7dd in std::shared_ptr<UserDb>::shared_ptr<std::allocator<void>, std::shared_ptr<oatpp::postgresql::Executor>&> (this=0x7fffffffcf48, __tag=..., __args=warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<oatpp::postgresql::Executor, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<oatpp::postgresql::Executor, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'

std::shared_ptr<oatpp::postgresql::Executor> (use count 4, weak count 0) = {...}) at /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/shared_ptr.h:464
#20 0x0000555555e2f69c in std::make_shared<UserDb, std::shared_ptr<oatpp::postgresql::Executor>&> (__args=warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<oatpp::postgresql::Executor, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<oatpp::postgresql::Executor, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'

std::shared_ptr<oatpp::postgresql::Executor> (use count 4, weak count 0) = {...}) at /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/shared_ptr.h:1009
#21 0x0000555555e2f239 in DatabaseComponent::userDb::{lambda()#1}::operator()() const (this=0x7fffffffcf40)
    at /home/manju/tools/oatpp_repos/examples/example-jwt/src/DatabaseComponent.hpp:82
#22 0x0000555555e1fcd5 in DatabaseComponent::DatabaseComponent (this=0x7fffffffd6e0) at /home/manju/tools/oatpp_repos/examples/example-jwt/src/DatabaseComponent.hpp:66
#23 0x0000555555e1e2d4 in AppComponent::AppComponent (this=0x7fffffffd4b0) at /home/manju/tools/oatpp_repos/examples/example-jwt/src/AppComponent.hpp:25
#24 0x0000555555e1d417 in run () at /home/manju/tools/oatpp_repos/examples/example-jwt/src/App.cpp:16
#25 0x0000555555e1dfa0 in main (argc=1, argv=0x7fffffffd878) at /home/manju/tools/oatpp_repos/examples/example-jwt/src/App.cpp:48
(gdb) 
#0  0x00007ffff767290d in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.3
#1  0x00007ffff7678c5b in ENGINE_init () from /lib/x86_64-linux-gnu/libcrypto.so.3
#2  0x00007ffff76aefa1 in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.3
#3  0x00007ffff79843d3 in SSL_CTX_new_ex () from /lib/x86_64-linux-gnu/libssl.so.3
#4  0x00007ffff7f7f3dd in ?? () from /lib/x86_64-linux-gnu/libpq.so.5
#5  0x00007ffff7f68e1a in PQconnectPoll () from /lib/x86_64-linux-gnu/libpq.so.5
#6  0x00007ffff7f6ae10 in ?? () from /lib/x86_64-linux-gnu/libpq.so.5
#7  0x00007ffff7f6af08 in PQconnectdb () from /lib/x86_64-linux-gnu/libpq.so.5
#8  0x0000555555f04abc in oatpp::postgresql::ConnectionProvider::get (this=0x5555563c3db0)
    at /home/manju/tools/oatpp_repos/oatpp-postgresql/src/oatpp-postgresql/ConnectionProvider.cpp:43
#9  0x0000555555e347df in oatpp::provider::PoolTemplate<oatpp::postgresql::Connection, oatpp::postgresql::ConnectionAcquisitionProxy>::get (_this=warning: RTTI symbol not found for class 'std::_Sp_counted_ptr<oatpp::provider::Pool<oatpp::provider::Provider<oatpp::postgresql::Connection>, oatpp::postgresql::Connection, oatpp::postgresql::ConnectionAcquisitionProxy>*, (__gnu_cxx::_Lock_policy)2>'
warning: RTTI symbol not found for class 'std::_Sp_counted_ptr<oatpp::provider::Pool<oatpp::provider::Provider<oatpp::postgresql::Connection>, oatpp::postgresql::Connection, oatpp::postgresql::ConnectionAcquisitionProxy>*, (__gnu_cxx::_Lock_policy)2>'

std::shared_ptr<oatpp::provider::PoolTemplate<oatpp::postgresql::Connection, oatpp::postgresql::ConnectionAcquisitionProxy>> (use count 4, weak count 1) = {...})
    at /usr/local/include/oatpp-1.3.0/oatpp/oatpp/core/provider/Pool.hpp:266
#10 0x0000555555e3047e in oatpp::provider::Pool<oatpp::provider::Provider<oatpp::postgresql::Connection>, oatpp::postgresql::Connection, oatpp::postgresql::ConnectionAcquisitionProxy>::get (this=0x5555563c53d0) at /usr/local/include/oatpp-1.3.0/oatpp/oatpp/core/provider/Pool.hpp:462
#11 0x0000555555f0863c in oatpp::postgresql::Executor::getConnection (this=0x5555563c56f0) at /home/manju/tools/oatpp_repos/oatpp-postgresql/src/oatpp-postgresql/Executor.cpp:299
#12 0x00005555560429cc in oatpp::orm::SchemaMigration::migrate (this=0x7fffffffcbd0) at /home/manju/tools/oatpp_repos/oatpp/src/oatpp/orm/SchemaMigration.cpp:50
#13 0x0000555555e3c04b in UserDb::UserDb (this=0x5555563c4810, executor=warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<oatpp::postgresql::Executor, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<oatpp::postgresql::Executor, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
std::shared_ptr<oatpp::orm::Executor> (use count 4, weak count 0) = {...})
    at /home/manju/tools/oatpp_repos/examples/example-jwt/src/db/UserDb.hpp:23
#14 0x0000555555e3be8e in std::_Construct<UserDb, std::shared_ptr<oatpp::postgresql::Executor>&> (__p=0x5555563c4810, __args=warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<oatpp::postgresql::Executor, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<oatpp::postgresql::Executor, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'

std::shared_ptr<oatpp::postgresql::Executor> (use count 4, weak count 0) = {...}) at /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/stl_construct.h:119
#15 0x0000555555e3bcd1 in std::allocator_traits<std::allocator<void> >::construct<UserDb, std::shared_ptr<oatpp::postgresql::Executor>&> (__p=0x5555563c4810, __args=warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<oatpp::postgresql::Executor, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<oatpp::postgresql::Executor, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'

std::shared_ptr<oatpp::postgresql::Executor> (use count 4, weak count 0) = {...}) at /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/alloc_traits.h:635
#16 0x0000555555e3ba6a in std::_Sp_counted_ptr_inplace<UserDb, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<std::shared_ptr<oatpp::postgresql::Executor>&> (this=0x5555563c4800, __a=..., __args=warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<oatpp::postgresql::Executor, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<oatpp::postgresql::Executor, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
std::shared_ptr<oatpp::postgresql::Executor> (use count 4, weak count 0) = {...})
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/shared_ptr_base.h:604
#17 0x0000555555e3b8dd in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<UserDb, std::allocator<void>, std::shared_ptr<oatpp::postgresql::Executor>&> (
    this=0x7fffffffcf50, __p=@0x7fffffffcf48: 0x0, __a=..., __args=warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<oatpp::postgresql::Executor, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<oatpp::postgresql::Executor, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
std::shared_ptr<oatpp::postgresql::Executor> (use count 4, weak count 0) = {...})
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/shared_ptr_base.h:972
#18 0x0000555555e3b840 in std::__shared_ptr<UserDb, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<void>, std::shared_ptr<oatpp::postgresql::Executor>&> (
    this=0x7fffffffcf48, __tag=..., __args=warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<oatpp::postgresql::Executor, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<oatpp::postgresql::Executor, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
std::shared_ptr<oatpp::postgresql::Executor> (use count 4, weak count 0) = {...})
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/shared_ptr_base.h:1712
#19 0x0000555555e3b7dd in std::shared_ptr<UserDb>::shared_ptr<std::allocator<void>, std::shared_ptr<oatpp::postgresql::Executor>&> (this=0x7fffffffcf48, __tag=..., __args=warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<oatpp::postgresql::Executor, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<oatpp::postgresql::Executor, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'

std::shared_ptr<oatpp::postgresql::Executor> (use count 4, weak count 0) = {...}) at /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/shared_ptr.h:464
#20 0x0000555555e2f69c in std::make_shared<UserDb, std::shared_ptr<oatpp::postgresql::Executor>&> (__args=warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<oatpp::postgresql::Executor, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<oatpp::postgresql::Executor, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'

std::shared_ptr<oatpp::postgresql::Executor> (use count 4, weak count 0) = {...}) at /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/shared_ptr.h:1009
#21 0x0000555555e2f239 in DatabaseComponent::userDb::{lambda()#1}::operator()() const (this=0x7fffffffcf40)
    at /home/manju/tools/oatpp_repos/examples/example-jwt/src/DatabaseComponent.hpp:82
#22 0x0000555555e1fcd5 in DatabaseComponent::DatabaseComponent (this=0x7fffffffd6e0) at /home/manju/tools/oatpp_repos/examples/example-jwt/src/DatabaseComponent.hpp:66
#23 0x0000555555e1e2d4 in AppComponent::AppComponent (this=0x7fffffffd4b0) at /home/manju/tools/oatpp_repos/examples/example-jwt/src/AppComponent.hpp:25
#24 0x0000555555e1d417 in run () at /home/manju/tools/oatpp_repos/examples/example-jwt/src/App.cpp:16
#25 0x0000555555e1dfa0 in main (argc=1, argv=0x7fffffffd878) at /home/manju/tools/oatpp_repos/examples/example-jwt/src/App.cpp:48
(gdb)

**Comment by manjus3** [comment]
Hi @lganzzzo,

So I did some more debugging on the above problem, but I did it in the example-crud repository, which doesn't have any references to the jwt-cpp repo.  In the CMakeListst.txt file, I add the following two lines:

SET(CMAKE_CXX_COMPILER "clang++")
SET (CMAKE_CXX_FLAGS_DEBUG "-O0 -g -fstack-check -fstack-protector-strong -finstrument-functions -fsanitize=address -fsanitize=leak -fsanitize=undefined -fno-omit-frame-pointer -static-libsan")

And here's what I got below. Seems serious enough to take a closer look at your macros. I think this is what is causing the problem I mentioned in the previous post.

D |2022-07-13 22:55:41 1657778141523059| UserDb:Migration - OK. Version=1.
/home/manju/tools/oatpp_repos/examples/example-crud/src/dto/PageDto.hpp:14:3: runtime error: member access within address 0x7ffcc2788220 which does not point to an object of type 'PageDto<oatpp::data::mapping::type::DTOWrapper<UserDto>>::Z__CLASS' (aka 'PageDto<oatpp::data::mapping::type::DTOWrapper<UserDto>>')
0x7ffcc2788220: note: object has a possibly invalid vptr: abs(offset to top) too big
 ad 55 00 00  40 82 78 c2 fc 7f 00 00  c0 83 78 c2 fc 7f 00 00  80 55 7a 97 ad 55 00 00  2e 25 3e 97
              ^~~~~~~~~~~~~~~~~~~~~~~
              possibly invalid vptr
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/manju/tools/oatpp_repos/examples/example-crud/src/dto/PageDto.hpp:14:3 in 
/home/manju/tools/oatpp_repos/examples/example-crud/src/dto/PageDto.hpp:15:3: runtime error: member access within address 0x7ffcc2788220 which does not point to an object of type 'PageDto<oatpp::data::mapping::type::DTOWrapper<UserDto>>::Z__CLASS' (aka 'PageDto<oatpp::data::mapping::type::DTOWrapper<UserDto>>')
0x7ffcc2788220: note: object has a possibly invalid vptr: abs(offset to top) too big
 ad 55 00 00  80 4b 00 00 30 60 00 00  80 4b 00 00 30 60 00 00  80 4b 00 00 30 60 00 00  80 83 78 c2
              ^~~~~~~~~~~~~~~~~~~~~~~
              possibly invalid vptr
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/manju/tools/oatpp_repos/examples/example-crud/src/dto/PageDto.hpp:15:3 in 
/home/manju/tools/oatpp_repos/examples/example-crud/src/dto/PageDto.hpp:16:3: runtime error: member access within address 0x7ffcc2788220 which does not point to an object of type 'PageDto<oatpp::data::mapping::type::DTOWrapper<UserDto>>::Z__CLASS' (aka 'PageDto<oatpp::data::mapping::type::DTOWrapper<UserDto>>')
0x7ffcc2788220: note: object has a possibly invalid vptr: abs(offset to top) too big
 ad 55 00 00  b0 4b 00 00 30 60 00 00  b0 4b 00 00 30 60 00 00  b0 4b 00 00 30 60 00 00  80 83 78 c2
              ^~~~~~~~~~~~~~~~~~~~~~~
              possibly invalid vptr
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/manju/tools/oatpp_repos/examples/example-crud/src/dto/PageDto.hpp:16:3 in 
/home/manju/tools/oatpp_repos/examples/example-crud/src/dto/PageDto.hpp:17:3: runtime error: member access within address 0x7ffcc2788220 which does not point to an object of type 'PageDto<oatpp::data::mapping::type::DTOWrapper<UserDto>>::Z__CLASS' (aka 'PageDto<oatpp::data::mapping::type::DTOWrapper<UserDto>>')
0x7ffcc2788220: note: object has a possibly invalid vptr: abs(offset to top) too big
 ad 55 00 00  e0 4b 00 00 30 60 00 00  e0 4b 00 00 30 60 00 00  e0 4b 00 00 30 60 00 00  80 83 78 c2
              ^~~~~~~~~~~~~~~~~~~~~~~
              possibly invalid vptr
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/manju/tools/oatpp_repos/examples/example-crud/src/dto/PageDto.hpp:17:3 in 
/home/manju/tools/oatpp_repos/examples/example-crud/src/dto/UserDto.hpp:18:3: runtime error: member access within address 0x7ffcc2787fa0 which does not point to an object of type 'UserDto::Z__CLASS' (aka 'UserDto')
0x7ffcc2787fa0: note: object has a possibly invalid vptr: abs(offset to top) too big
 fc 7f 00 00  a0 7c 00 00 40 60 00 00  e0 7f 78 c2 fc 7f 00 00  f0 80 78 c2 fc 7f 00 00  d9 27 3e 97
              ^~~~~~~~~~~~~~~~~~~~~~~
              possibly invalid vptr
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/manju/tools/oatpp_repos/examples/example-crud/src/dto/UserDto.hpp:18:3 in 
/home/manju/tools/oatpp_repos/examples/example-crud/src/dto/UserDto.hpp:19:3: runtime error: member access within address 0x7ffcc2787fa0 which does not point to an object of type 'UserDto::Z__CLASS' (aka 'UserDto')
0x7ffcc2787fa0: note: object has a possibly invalid vptr: abs(offset to top) too big
 fc 7f 00 00  20 80 78 c2 fc 7f 00 00  28 bf 55 97 ad 55 00 00  19 96 75 4e 25 a4 e0 c5  01 00 00 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              possibly invalid vptr
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/manju/tools/oatpp_repos/examples/example-crud/src/dto/UserDto.hpp:19:3 in 
/home/manju/tools/oatpp_repos/examples/example-crud/src/dto/UserDto.hpp:20:3: runtime error: member access within address 0x7ffcc2787fa0 which does not point to an object of type 'UserDto::Z__CLASS' (aka 'UserDto')
0x7ffcc2787fa0: note: object has a possibly invalid vptr: abs(offset to top) too big
 fc 7f 00 00  20 80 78 c2 fc 7f 00 00  28 bf 55 97 ad 55 00 00  18 ec 81 96 f3 ad 63 98  01 00 00 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              possibly invalid vptr
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/manju/tools/oatpp_repos/examples/example-crud/src/dto/UserDto.hpp:20:3 in 
/home/manju/tools/oatpp_repos/examples/example-crud/src/dto/UserDto.hpp:21:3: runtime error: member access within address 0x7ffcc2787fa0 which does not point to an object of type 'UserDto::Z__CLASS' (aka 'UserDto')
0x7ffcc2787fa0: note: object has a possibly invalid vptr: abs(offset to top) too big
 fc 7f 00 00  20 80 78 c2 fc 7f 00 00  28 bf 55 97 ad 55 00 00  0d 7a 0d c9 5a 2f c2 e2  01 00 00 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              possibly invalid vptr
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/manju/tools/oatpp_repos/examples/example-crud/src/dto/UserDto.hpp:21:3 in 
/home/manju/tools/oatpp_repos/examples/example-crud/src/dto/UserDto.hpp:22:3: runtime error: member access within address 0x7ffcc2787fa0 which does not point to an object of type 'UserDto::Z__CLASS' (aka 'UserDto')
0x7ffcc2787fa0: note: object has a possibly invalid vptr: abs(offset to top) too big
 fc 7f 00 00  20 80 78 c2 fc 7f 00 00  28 bf 55 97 ad 55 00 00  eb 89 14 68 45 69 45 54  01 00 00 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              possibly invalid vptr
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/manju/tools/oatpp_repos/examples/example-crud/src/dto/UserDto.hpp:22:3 in 
/home/manju/tools/oatpp_repos/examples/example-crud/src/dto/StatusDto.hpp:17:3: runtime error: member access within address 0x7ffcc2788280 which does not point to an object of type 'StatusDto::Z__CLASS' (aka 'StatusDto')
0x7ffcc2788280: note: object has a possibly invalid vptr: abs(offset to top) too big
 ad 55 00 00  50 7e 00 00 40 60 00 00  08 7c 24 98 ad 55 00 00  08 7c 24 98 ad 55 00 00  08 7c 24 98
              ^~~~~~~~~~~~~~~~~~~~~~~
              possibly invalid vptr
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/manju/tools/oatpp_repos/examples/example-crud/src/dto/StatusDto.hpp:17:3 in 
/home/manju/tools/oatpp_repos/examples/example-crud/src/dto/StatusDto.hpp:22:3: runtime error: member access within address 0x7ffcc2788280 which does not point to an object of type 'StatusDto::Z__CLASS' (aka 'StatusDto')
0x7ffcc2788280: note: object has invalid vptr
 ad 55 00 00  02 00 00 00 00 00 00 00  06 00 00 00 00 00 00 80  00 00 00 00 00 00 00 00  00 00 00 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              invalid vptr
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/manju/tools/oatpp_repos/examples/example-crud/src/dto/StatusDto.hpp:22:3 in 
/home/manju/tools/oatpp_repos/examples/example-crud/src/dto/StatusDto.hpp:27:3: runtime error: member access within address 0x7ffcc2788280 which does not point to an object of type 'StatusDto::Z__CLASS' (aka 'StatusDto')
0x7ffcc2788280: note: object has a possibly invalid vptr: abs(offset to top) too big
 ad 55 00 00  50 4e 00 00 30 60 00 00  b0 83 78 c2 fc 7f 00 00  50 4e 00 00 30 60 00 00  40 7c 24 98
              ^~~~~~~~~~~~~~~~~~~~~~~
              possibly invalid vptr
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/manju/tools/oatpp_repos/examples/example-crud/src/dto/StatusDto.hpp:27:3 in 
 D |2022-07-13 22:55:41 1657778141534698| Server:Running on port 8000...
